import { spawnSync } from 'node:child_process';
import { accessSync, chmodSync, constants, writeFileSync } from 'node:fs';
import { delimiter, isAbsolute, join } from 'node:path';
import { parseArgs, shellQuote } from '../lib/args.mjs';
import { ExitCode, OpcError, UsageError } from '../lib/opc-error.mjs';
import { openApi } from '../lib/context.mjs';
import { assertId } from '../lib/api.mjs';
import { attachSecretPath, writeAttachSecret } from '../lib/server.mjs';
import { listJobs } from '../lib/jobs.mjs';
import { renderAttach } from '../lib/render.mjs';

export const PANE_SCRIPT_NAME = 'attach-pane.sh';
export const PANE_SCRIPT = `#!/bin/sh
# Generated by opc (attach --pane). Reads the OpenCode server password from a
# 0600 file inside the pane, so it never appears in any process argv.
set -eu
secret_file=$1
opencode_bin=$2
shift 2
OPENCODE_SERVER_PASSWORD=$(cat "$secret_file")
export OPENCODE_SERVER_PASSWORD
exec "$opencode_bin" "$@"
`;

const SPEC = { flags: { pane: { type: 'boolean' }, json: { type: 'boolean' }, cwd: { type: 'string' } }, allowPositionals: true };

export function resolveExecutable(name, pathEnv = process.env.PATH ?? '') {
  if (isAbsolute(name)) return name;
  for (const dir of String(pathEnv).split(delimiter).filter(Boolean)) {
    const candidate = join(dir, name);
    try { accessSync(candidate, constants.X_OK); return candidate; } catch { /* continue */ }
  }
  return name;
}

export function buildAttachArgs({ url, sessionID, directory }) {
  return ['attach', url, ...(sessionID ? ['-s', sessionID] : []), '--dir', directory];
}

function lastJobSession(ctx) {
  const jobs = listJobs(ctx.stateDir, { claudeSessionId: ctx.claudeSessionId, all: !ctx.claudeSessionId })
    .filter((job) => job.sessionID && !job.groupId)
    .sort((a, b) => String(b.updatedAt ?? b.createdAt ?? '').localeCompare(String(a.updatedAt ?? a.createdAt ?? '')));
  return jobs[0]?.sessionID ?? null;
}

function envWithoutSecrets(env) {
  const copy = { ...env };
  delete copy.OPENCODE_SERVER_PASSWORD;
  delete copy.OPC_SERVER_PASSWORD;
  return copy;
}

export async function run(ctx, argv) {
  const { flags, positionals } = parseArgs(argv, SPEC);
  const explicit = positionals[0] ? assertId('ses', positionals[0], 'sessão') : null;
  if (flags.pane && !ctx.env.TMUX) {
    throw new UsageError('NOT_IN_TMUX', '--pane só funciona dentro do tmux ($TMUX vazio). Rode /opc:attach sem --pane e use a linha exibida num terminal.');
  }
  const conn = await openApi(ctx);
  try {
    const { server, api } = conn;
    const sessionID = explicit ?? lastJobSession(ctx);
    if (sessionID) await api.getSession(sessionID);
    const attached = Boolean(server.attached);
    if (flags.pane && attached) {
      throw new UsageError('PANE_ATTACHED_MODE', '--pane não funciona com OPC_SERVER_URL porque o opc não guarda a senha do servidor externo. Use a linha exibida sem --pane.');
    }
    const directory = ctx.workspaceRoot;
    const credential = attached
      ? { type: 'env', name: 'OPC_SERVER_PASSWORD' }
      : { type: 'file', path: attachSecretPath(ctx.stateDir) };
    if (!attached) writeAttachSecret(ctx.stateDir, server.password);
    const attachArgs = buildAttachArgs({ url: server.url, sessionID, directory });
    const info = { url: server.url, sessionID, directory, attached, credential, argv: ['opencode', ...attachArgs] };

    if (flags.pane) {
      const scriptPath = join(ctx.stateDir, PANE_SCRIPT_NAME);
      writeFileSync(scriptPath, PANE_SCRIPT, { mode: 0o700 });
      chmodSync(scriptPath, 0o700);
      const opencodeBin = resolveExecutable(ctx.env.OPC_ATTACH_OPENCODE_BIN ?? 'opencode', ctx.env.PATH);
      const paneCommand = ['/bin/sh', scriptPath, credential.path, opencodeBin, ...attachArgs].map(shellQuote).join(' ');
      const res = spawnSync('tmux', ['split-window', '-h', '-P', '-F', '#{pane_id}', '-c', directory, paneCommand], {
        env: envWithoutSecrets(ctx.env), encoding: 'utf8', shell: false,
      });
      if (res.error || res.status !== 0) {
        throw new OpcError('TMUX_FAILED', 'tmux split-window falhou ao abrir o pane.', { exitCode: ExitCode.USAGE });
      }
      info.pane = { id: String(res.stdout).trim() };
    }

    if (flags.json) ctx.json(info);
    else ctx.out(renderAttach(info));
    return ExitCode.OK;
  } finally {
    conn.close();
  }
}
