import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { runCli, readFakeState } from '../helpers.mjs';
import { setupConclave, conclave, requestsBySchema, fakeRequests, textOf, DS, QW, KM, TRIO } from './_conclave-helpers.mjs';
const Q = 'Should the storage layer add a write-ahead log?';
test('opinion: three members answer blind in read-only sessions; --json returns the full package', async (t) => {
 const {env,cwd}=setupConclave(t,{scenario:'conclave-opinion'}); const res=await conclave(['--models',TRIO,'--json',Q],{env,cwd}); assert.equal(res.code,0,res.stderr); const pkg=res.json; assert.match(pkg.jobId,/^conc-/); assert.equal(pkg.status,'completed'); assert.equal(pkg.mode,'opinion'); assert.deepEqual(pkg.rounds,{requested:1,completed:1}); assert.equal(pkg.final.responses.length,3); assert.deepEqual(pkg.failures,[]); assert.equal(Object.keys(pkg).at(-1),'composition'); assert.deepEqual(pkg.composition.map(c=>c.label),['A','B','C']); assert.deepEqual(new Set(pkg.composition.map(c=>c.model)),new Set([DS,QW,KM])); assert.deepEqual(pkg.judge,{type:'claude',status:'pending'}); const members=requestsBySchema(env,'ConclaveMember'); assert.equal(members.length,3); assert.ok(members.every(r=>r.body.format?.type==='json_schema'?textOf(r.body).includes(Q):textOf(r.body).includes(Q))); assert.equal(new Set(members.map(r=>r.body.model.modelID)).size,3); const created=readFakeState(env).requests.filter(r=>r.method==='POST'&&r.path==='/session'); assert.equal(created.length,3); for(const s of created){assert.match(s.body.title,/^OPC: conclave: /); assert.deepEqual(s.body.permission[0],{permission:'*',pattern:'*',action:'deny'}); assert.ok(!s.body.permission.some(rule=>rule.permission==='bash'&&rule.action==='allow'));}
});
test('opinion without --json renders markdown with the composition after the synthesis',async t=>{const {env,cwd}=setupConclave(t,{scenario:'conclave-opinion'});const res=await conclave(['--models',`${DS},${QW}`,Q],{env,cwd});assert.equal(res.code,0,res.stderr);assert.match(res.stdout,/# opc conclave · opinion/);assert.match(res.stdout,/### Membro A · confiança/);assert.match(res.stdout,/Juiz: Claude\. Sintetize com a skill `opc-conclave`/);assert.ok(res.stdout.indexOf('## Composição')>res.stdout.indexOf('## Síntese'));const before=res.stdout.slice(0,res.stdout.indexOf('## Composição'));assert.doesNotMatch(before,/omniroute-personal\/opencode-go/);assert.match(res.stderr,/\[opc\] conclave conc-/);});
test('background: returns the id at once; status --wait and result --json deliver the package',async t=>{const {env,cwd}=setupConclave(t,{scenario:'conclave-opinion'});const started=await conclave(['--models',TRIO,'--background','--json',Q],{env,cwd});assert.equal(started.code,0,started.stderr);const {jobId}=started.json;assert.match(jobId,/^conc-/);const waited=await runCli(['status',jobId,'--wait','--timeout-ms','60000'],{env,cwd});assert.equal(waited.code,0,waited.stderr);const result=await runCli(['result',jobId,'--json'],{env,cwd});assert.equal(result.code,0,result.stderr);const {group,members}=JSON.parse(result.stdout);assert.equal(members.length,3);assert.equal(group.result.jobId,jobId);assert.equal(group.result.status,'completed');assert.equal(group.result.final.responses.length,3);const rendered=await runCli(['result',jobId],{env,cwd});assert.match(rendered.stdout,/# opc conclave · opinion/);});
test('member job records carry role, model and session; the group links them',async t=>{const {env,cwd}=setupConclave(t,{scenario:'conclave-opinion'});const res=await conclave(['--models',TRIO,'--json',Q],{env,cwd});assert.equal(res.code,0,res.stderr);const files=[];const walk=dir=>{for(const e of fs.readdirSync(dir,{withFileTypes:true})){const full=path.join(dir,e.name);if(e.isDirectory())walk(full);else if(/\/jobs\/[^/]+\.json$/.test(full))files.push(full);}};walk(path.join(env.OPC_DATA_DIR,'state'));const members=files.map(f=>JSON.parse(fs.readFileSync(f,'utf8'))).filter(j=>j.groupId===res.json.jobId);assert.equal(members.length,3);for(const m of members){assert.match(m.role,/^member:[ABC]$/);assert.equal(m.status,'completed');assert.ok(m.sessionID);assert.equal(res.json.composition.find(c=>`member:${c.label}`===m.role).model,m.model);}});
test('question reaches every member intact through --raw-args-stdin',async t=>{const {env,cwd}=setupConclave(t,{scenario:'conclave-opinion'});const question="Is `rm -rf $(pwd)` \"safe\"? don't\n$(touch pwned) — ção 🚀";const res=await runCli(['conclave','--raw-args-stdin'],{env,cwd,stdin:`--models ${DS},${QW} --json ${question}\n`});assert.equal(res.code,0,res.stderr);assert.equal(fs.existsSync(path.join(cwd,'pwned')),false);for(const r of requestsBySchema(env,'ConclaveMember'))assert.ok(textOf(r.body).includes(question));assert.equal(JSON.parse(res.stdout).question,question);});
test('inside OpenCode server refuses before connecting',async t=>{const {env,cwd}=setupConclave(t,{scenario:'conclave-opinion'});const res=await conclave(['--models',TRIO,Q],{env:{...env,OPC_INSIDE_SERVER:'1'},cwd});assert.equal(res.code,4,res.stderr);assert.match(res.stderr,/INSIDE_SERVER|servidor OpenCode/);assert.equal(fakeRequests(env).length,0);});
