import { test } from 'node:test';
import assert from 'node:assert/strict';
import { runWithFallback, describeStop } from '../../plugins/opc/scripts/lib/routing.mjs';

const A = { providerID: 'p', modelID: 'a', full: 'p/a', source: 'routing.tasks.ask' };
const B = { providerID: 'p', modelID: 'b', full: 'p/b', source: 'routing.tasks.ask' };
const C = { providerID: 'p', modelID: 'c', full: 'p/c', source: 'routing.tasks.ask' };
const ok = (model) => ({ status: 'completed', sessionID: `ses_${model.modelID}`, finalText: `from ${model.modelID}`, toolsRan: false, touchedFiles: [] });
const fail = (model, extra = {}) => ({ status: 'failed', sessionID: `ses_${model.modelID}`, errorClass: 'recoverable', errorType: 'APIError', errorMessage: 'rate limited', toolsRan: false, touchedFiles: [], ...extra });
function harness(script) {
  const calls = []; const sleeps = [];
  return { calls, sleeps, runAttempt: async (candidate, index) => { calls.push({ model: candidate.full, index }); return script(candidate, index); }, sleep: async (ms) => { sleeps.push(ms); return true; } };
}

test('recoverable failure falls back to the next candidate and records attempts[]', async () => {
  const h = harness((c, i) => (i === 0 ? fail(c) : ok(c)));
  const out = await runWithFallback({ candidates: [A, B, C], fallbackEligible: true, fallbackCfg: { enabled: true, maxAttempts: 3 }, runAttempt: h.runAttempt, sleep: h.sleep });
  assert.equal(out.stopReason, 'completed'); assert.equal(out.result.finalText, 'from b');
  assert.deepEqual(h.calls, [{ model: 'p/a', index: 0 }, { model: 'p/b', index: 1 }]); assert.deepEqual(h.sleeps, [2000]); assert.equal(out.fallbackUsed, true);
  assert.deepEqual(out.attempts.map(({ model, sessionID, status, errorClass, errorType }) => ({ model, sessionID, status, errorClass, errorType })), [
    { model: 'p/a', sessionID: 'ses_a', status: 'failed', errorClass: 'recoverable', errorType: 'APIError' },
    { model: 'p/b', sessionID: 'ses_b', status: 'completed', errorClass: null, errorType: null },
  ]);
  for (const a of out.attempts) assert.ok(a.startedAt && a.endedAt);
});
test('first-try success runs one attempt and never sleeps', async () => { const h = harness((c) => ok(c)); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'completed'); assert.equal(out.fallbackUsed, false); assert.deepEqual(h.sleeps, []); });
test('backoff grows 2s then 4s across attempts', async () => { const h = harness((c, i) => (i < 2 ? fail(c) : ok(c))); const out = await runWithFallback({ candidates: [A, B, C], fallbackEligible: true, fallbackCfg: { maxAttempts: 3 }, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'completed'); assert.deepEqual(h.sleeps, [2000, 4000]); });
test('custom backoff is used when injected', async () => { const h = harness((c, i) => (i === 0 ? fail(c) : ok(c))); await runWithFallback({ candidates: [A, B], fallbackEligible: true, backoffMs: [7], runAttempt: h.runAttempt, sleep: h.sleep }); assert.deepEqual(h.sleeps, [7]); });
test('maxAttempts caps the number of attempts', async () => { const h = harness((c) => fail(c)); const out = await runWithFallback({ candidates: [A, B, C], fallbackEligible: true, fallbackCfg: { maxAttempts: 2 }, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'max-attempts'); assert.equal(h.calls.length, 2); });
test('running out of candidates stops with exhausted', async () => { const h = harness((c) => fail(c)); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, fallbackCfg: { maxAttempts: 5 }, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'exhausted'); assert.equal(h.calls.length, 2); });
test('not eligible (explicit --model or single-value level) never falls back', async () => { const h = harness((c) => fail(c)); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: false, fallbackCfg: { maxAttempts: 3 }, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'not-eligible'); assert.equal(h.calls.length, 1); assert.deepEqual(h.sleeps, []); });
test('routing.fallback.enabled false never falls back', async () => { const h = harness((c) => fail(c)); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, fallbackCfg: { enabled: false }, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'not-eligible'); assert.equal(h.calls.length, 1); });
test('fatal error never falls back', async () => { const h = harness((c) => fail(c, { errorClass: 'fatal', errorType: 'ProviderAuthError' })); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'fatal'); assert.equal(h.calls.length, 1); });
test('cancelled turn never falls back', async () => { const h = harness(() => ({ status: 'cancelled', sessionID: 'ses_a', toolsRan: false, touchedFiles: [] })); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'cancelled'); assert.equal(h.calls.length, 1); });
test('server_lost never falls back', async () => { const h = harness((c) => fail(c, { errorCode: 'server_lost', errorType: 'server_lost' })); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'server-lost'); assert.equal(h.calls.length, 1); });
test('--write turn where tools ran never falls back', async () => { const h = harness((c) => fail(c, { toolsRan: true, touchedFiles: ['src/app.js'], toolNames: ['edit'] })); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, write: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'write-tools-ran'); assert.equal(h.calls.length, 1); });
test('--write turn with no tool run may fall back', async () => { const h = harness((c, i) => (i === 0 ? fail(c) : ok(c))); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, write: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'completed'); assert.equal(h.calls.length, 2); });
test('read-only turn where tools ran may fall back', async () => { const h = harness((c, i) => (i === 0 ? fail(c, { toolsRan: true }) : ok(c))); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, write: false, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'completed'); });
test('RetryCapExceeded (recoverable) falls back like any recoverable error', async () => { const h = harness((c, i) => (i === 0 ? fail(c, { errorType: 'RetryCapExceeded' }) : ok(c))); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep }); assert.equal(out.stopReason, 'completed'); assert.equal(out.attempts[0].errorType, 'RetryCapExceeded'); });
test('ContextOverflowError falls back only to a candidate with a larger context', async () => { const limits = { 'p/a': 1000, 'p/b': 500, 'p/c': 4000 }; const h = harness((c, i) => (i === 0 ? fail(c, { errorClass: 'fatal', errorType: 'ContextOverflowError' }) : ok(c))); const out = await runWithFallback({ candidates: [A, B, C], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep, contextLimitOf: (c) => limits[c.full] }); assert.equal(out.stopReason, 'completed'); assert.deepEqual(h.calls.map((c) => c.model), ['p/a', 'p/c']); });
test('ContextOverflowError without a larger candidate is fatal', async () => { const limits = { 'p/a': 1000, 'p/b': 500 }; const h = harness((c) => fail(c, { errorType: 'ContextOverflowError' })); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep, contextLimitOf: (c) => limits[c.full] }); assert.equal(out.stopReason, 'fatal'); assert.equal(h.calls.length, 1); });
test('abort during backoff stops with cancelled and runs no further attempt', async () => { const ac = new AbortController(); const h = harness((c) => fail(c)); const out = await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, signal: ac.signal, sleep: async () => { ac.abort(); return false; } }); assert.equal(out.stopReason, 'cancelled'); assert.equal(h.calls.length, 1); });
test('hooks are called in order with attempt data', async () => { const events = []; const h = harness((c, i) => (i === 0 ? fail(c) : ok(c))); await runWithFallback({ candidates: [A, B], fallbackEligible: true, runAttempt: h.runAttempt, sleep: h.sleep, onAttemptStart: (c, i) => events.push(`start:${c.full}:${i}`), onAttemptEnd: (rec, res, i) => events.push(`end:${rec.model}:${res.status}:${i}`), onBackoff: (ms, next) => events.push(`backoff:${ms}:${next.full}`) }); assert.deepEqual(events, ['start:p/a:0', 'end:p/a:failed:0', 'backoff:2000:p/b', 'start:p/b:1', 'end:p/b:completed:1']); });
test('empty candidate list is a usage error', async () => { await assert.rejects(runWithFallback({ candidates: [], fallbackEligible: true, runAttempt: async () => ({}) }), (err) => err.code === 'NO_CANDIDATES' && err.exitCode === 2); });
test('describeStop explains write-tools-ran with touched files and tools', () => { const d = describeStop({ stopReason: 'write-tools-ran', result: { errorType: 'APIError', errorMessage: 'rate limited', touchedFiles: ['src/app.js'], toolNames: ['edit'] }, attempts: [{}] }); assert.equal(d.errorCode, 'WRITE_NO_FALLBACK'); assert.match(d.errorMessage, /Arquivos tocados: src\/app\.js/); assert.match(d.errorMessage, /Ferramentas executadas: edit/); });
test('describeStop handles missing files and tool names', () => { const d = describeStop({ stopReason: 'write-tools-ran', result: { errorType: 'APIError' }, attempts: [{}] }); assert.match(d.errorMessage, /\(nenhum registrado\)/); assert.match(d.errorMessage, /\(desconhecidas\)/); });
test('describeStop summarises an exhausted fallback and ignores single attempts', () => { const attempts = [{ model: 'p/a', errorType: 'APIError', status: 'failed' }, { model: 'p/b', errorType: 'RetryCapExceeded', status: 'failed' }]; const d = describeStop({ stopReason: 'exhausted', result: { errorMessage: 'limite ainda excedido' }, attempts }); assert.equal(d.errorCode, 'FALLBACK_EXHAUSTED'); assert.match(d.errorMessage, /1\) p\/a: APIError; 2\) p\/b: RetryCapExceeded/); assert.match(d.errorMessage, /Último erro: limite ainda excedido/); assert.equal(describeStop({ stopReason: 'max-attempts', result: {}, attempts: [attempts[0]] }), null); assert.equal(describeStop({ stopReason: 'completed', result: {}, attempts }), null); assert.equal(describeStop({ stopReason: 'fatal', result: {}, attempts }), null); });
